# Generated by Django 5.1.1 on 2024-09-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_comment_timeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
